# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20170822_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='lenenos',
            new_name='linenos',
        ),
    ]
